# Same as cloudbuild-prod.yaml except with version tagging.
steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - "-c"
  - docker build --network cloudbuild --no-cache --build-arg GH_CLIENT_SECRET="$$GH_CLIENT_SECRET" -t gcr.io/$PROJECT_ID/editor-dev-ui:latest -t gcr.io/$PROJECT_ID/editor-dev-ui:$_TAG .

images:
- gcr.io/$PROJECT_ID/editor-dev-ui
