title: Local Development
navTitle: Local
description: Develop projects using a local set of project files.

config:
  port: 8080
  mode: dev

partials:
- partial: spacer
  options:
  - large

- partial: hero
  title: Local development
  body: Use the editor.dev UI to edit files in a local project.

- partial: spacer
  options:
  - medium

- partial: local
  title: Searching for local project...
  body: "Run the following command in the main directory of your local project:"
  instructions:
    version: 14
    command: npx @blinkk/editor.dev

- partial: spacer
  options:
  - large
